codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  range: 60..90
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
        flags:
          - unittests
        paths:
          - project-nexus/
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "project-nexus/**/migrations/**"
  - "project-nexus/**/__pycache__/**"
  - "project-nexus/**/tests/**"

fixes:
  - "project-nexus/::"

flags:
  unittests:
    paths:
      - project-nexus/
    carryforward: true

comment:
  layout: "diff, flags, files"
  behavior: "default"
  require_changes: false
